apiVersion: 1

datasources:
  - name: PostgreSQL Test Results
    type: postgres
    uid: postgres-testresults
    orgId: 1
    access: proxy
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: 'grafana123'
    jsonData:
      database: testresults
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
